version: 2.1

executors:
  pyimage:
    working_directory: ~/poetry-docker
    docker:
      - image: circleci/python:3.7

commands:
  check:
    steps: 
      - run: 
          name: build image 
          command: |
            docker build -t poetry-docker .
            docker images
      - run: 
          name: check python executability
          command: docker run -it poetry-docker poetry run python -c "print('hello world')"

jobs: 
  is_buildable: 
    executor: 
      name: pyimage
    steps: 
      - checkout 
      - setup_remote_docker 
      - check

workflows: 
  availability_check: 
    jobs: 
      - is_buildable
