version: 2.1

executors:
  pyimage:
    working_directory: ~/poetry-docker
    docker:
      - image: circleci/python:3.7

commands:
  build:
    steps: 
      - run: 
          name: build image 
          command: |
            docker build -t poetry-docker .
            docker images


jobs: 
  is_buildable: 
    executor: 
      name: pyimage
    steps: 
      - checkout 
      - setup_remote_docker 
      - build

workflows: 
  availability_check: 
    jobs: 
      - is_buildable
